# Generated by Django 4.1 on 2022-09-06 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_customers(apps, schema_editor):
    Customer = apps.get_model('app_name', 'Customer')
    User = apps.get_model('auth', 'User')
    customers = [
        Customer(user=user, full_name=None, address=None)
        for user in User.objects.filter(customer=None)
    ]
    Customer.objects.bulk_create(customers)
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='admins')),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
